apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-phpfpm
  name: nginx-phpfpm
spec:
  volumes:
  - name: shared-files
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
        name: nginx-config
  containers:
  - image: nginx:latest
    name: nginx-container
    resources: {}
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  - image: php:7.2-fpm
    name: php-fpm-container
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html   
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {} 
    http {
      server {
        listen 8092;
        index index.html index.htm index.php;
        root  /var/www/html;
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-phpfpm
  name: nginx-phpfpm
spec:
  type: NodePort
  ports:
  - port: 8092
    protocol: TCP
    targetPort: 8092
    nodePort: 30012
  selector:
    run: nginx-phpfpm
status:
  loadBalancer: {}



