- name: install httpd and setup index.html
  hosts: all
  become: yes
  tasks:
  - name: install httpd
    package:
       name: httpd
       state: present
  - name: start service httpd, if not started
    service:
       name: httpd
       state: started
  - name: add content in index.html. create file if it does not exist and set file attributes
    copy:
       dest: /var/www/html/index.html
       content: This is a Nautilus sample file, created using Ansible!
       mode: "0644"
       owner: apache
       group: apache
  - name: Update content in index.html
    lineinfile:
       path: /var/www/html/index.html
       insertbefore: BOF
       line: Welcome to Nautilus Group!
